pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: VSBuild@1
  inputs:
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    configuration: '$(buildConfiguration)'

